//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bagımsız_Ozellikler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bagımsız_Ozellikler()
        {
            this.Konut = new HashSet<Konut>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> İlan_Tarihi { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> m2 { get; set; }
        public string Oda_sayisi { get; set; }
        public Nullable<int> Bina_yasi { get; set; }
        public Nullable<int> Bulundugu_kat { get; set; }
        public Nullable<int> Toplam_Kat { get; set; }
        public string Isıtma_Tipi { get; set; }
        public Nullable<int> Banyo_Sayısı { get; set; }
        public Nullable<bool> Balkon { get; set; }
        public Nullable<bool> Esyalı { get; set; }
        public Nullable<bool> Kullanım_durumu { get; set; }
        public Nullable<bool> Site_ici { get; set; }
        public Nullable<int> Aidat_TL_ { get; set; }
        public Nullable<bool> Krediye_uygun { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konut> Konut { get; set; }
    }
}
