//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DısOzellikler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DısOzellikler()
        {
            this.Konut = new HashSet<Konut>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Asansor { get; set; }
        public Nullable<bool> BuharOdası { get; set; }
        public Nullable<bool> Güvenlik { get; set; }
        public Nullable<bool> Hidrofor { get; set; }
        public Nullable<bool> IsıYalıtım { get; set; }
        public Nullable<bool> Jeneratör { get; set; }
        public Nullable<bool> KabloTV { get; set; }
        public Nullable<bool> KapalıGaraj { get; set; }
        public Nullable<bool> Kres { get; set; }
        public Nullable<bool> MüstakilHavuz { get; set; }
        public Nullable<bool> OtoPark { get; set; }
        public Nullable<bool> OyunParkı { get; set; }
        public Nullable<bool> Sauna { get; set; }
        public Nullable<bool> SesYalıtım { get; set; }
        public Nullable<bool> SporAlanı { get; set; }
        public Nullable<bool> SuDeposu { get; set; }
        public Nullable<bool> TenisKortu { get; set; }
        public Nullable<bool> Uydu { get; set; }
        public Nullable<bool> YangınMerdiveni { get; set; }
        public Nullable<bool> YüzmeHavuzu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konut> Konut { get; set; }
    }
}
