//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class IcOzellikler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IcOzellikler()
        {
            this.Konut = new HashSet<Konut>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Adsl { get; set; }
        public Nullable<bool> AhsapDograma { get; set; }
        public Nullable<bool> AkıllıEv { get; set; }
        public Nullable<bool> Alarm { get; set; }
        public Nullable<bool> AlaturkaTuvalet { get; set; }
        public Nullable<bool> AlüminyumDograma { get; set; }
        public Nullable<bool> AmerikanMutfak { get; set; }
        public Nullable<bool> AnkastreFırın { get; set; }
        public Nullable<bool> Asansor { get; set; }
        public Nullable<bool> Balkon { get; set; }
        public Nullable<bool> Barbekü { get; set; }
        public Nullable<bool> BeyazEsya { get; set; }
        public Nullable<bool> Boyalı { get; set; }
        public Nullable<bool> BulasıkMakinesi { get; set; }
        public Nullable<bool> Buzdolabı { get; set; }
        public Nullable<bool> DuvarKagıdı { get; set; }
        public Nullable<bool> DusaKabin { get; set; }
        public Nullable<bool> EbeveynBanyosu { get; set; }
        public Nullable<bool> Fiberİnternet { get; set; }
        public Nullable<bool> Fırın { get; set; }
        public Nullable<bool> GiyinmeOdası { get; set; }
        public Nullable<bool> GommeDolap { get; set; }
        public Nullable<bool> GoruntuluTelefon { get; set; }
        public Nullable<bool> Isıcam { get; set; }
        public Nullable<bool> Jakuzi { get; set; }
        public Nullable<bool> Kiler { get; set; }
        public Nullable<bool> Klima { get; set; }
        public Nullable<bool> Kuvet { get; set; }
        public Nullable<bool> LaminatZemin { get; set; }
        public Nullable<bool> Marley { get; set; }
        public Nullable<bool> Mobilya { get; set; }
        public Nullable<bool> PvcDograma { get; set; }
        public Nullable<bool> Panjur { get; set; }
        public Nullable<bool> ParkeZemin { get; set; }
        public Nullable<bool> SeramikZemin { get; set; }
        public Nullable<bool> SetUstuOcak { get; set; }
        public Nullable<bool> SpotAydınlanma { get; set; }
        public Nullable<bool> Teras { get; set; }
        public Nullable<bool> Termosifon { get; set; }
        public Nullable<bool> Vestiyer { get; set; }
        public Nullable<bool> Wi_Fi { get; set; }
        public Nullable<bool> CamasırKurutmaMakinesi { get; set; }
        public Nullable<bool> CamasırMakinesi { get; set; }
        public Nullable<bool> CamasırOdası { get; set; }
        public Nullable<bool> CelikKapı { get; set; }
        public Nullable<bool> Sofben { get; set; }
        public Nullable<bool> Somine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konut> Konut { get; set; }
    }
}
