//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konut
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Baslık { get; set; }
        public string Acıklama { get; set; }
        public int Durum_Id { get; set; }
        public Nullable<int> Bag_Ozellikler_Id { get; set; }
        public Nullable<int> Cephe_Id { get; set; }
        public Nullable<int> Adress_Id { get; set; }
        public Nullable<int> İcOzellik_Id { get; set; }
        public Nullable<int> DısOzellik_Id { get; set; }
        public Nullable<int> Muhit_Id { get; set; }
        public Nullable<int> Ulasım_Id { get; set; }
        public Nullable<int> Manzara_Id { get; set; }
        public Nullable<int> ResimTablo_Id { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Bagımsız_Ozellikler Bagımsız_Ozellikler { get; set; }
        public virtual Cephe Cephe { get; set; }
        public virtual DısOzellikler DısOzellikler { get; set; }
        public virtual Durum Durum { get; set; }
        public virtual IcOzellikler IcOzellikler { get; set; }
        public virtual Manzara Manzara { get; set; }
        public virtual Muhit Muhit { get; set; }
        public virtual ResimTablo ResimTablo { get; set; }
        public virtual Ulasim Ulasim { get; set; }
    }
}
