//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manzara
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Manzara()
        {
            this.Konut = new HashSet<Konut>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Bogaz { get; set; }
        public Nullable<bool> Deniz { get; set; }
        public Nullable<bool> Doga { get; set; }
        public Nullable<bool> Göl { get; set; }
        public Nullable<bool> Havuz { get; set; }
        public Nullable<bool> Sehir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konut> Konut { get; set; }
    }
}
