//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muhit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Muhit()
        {
            this.Konut = new HashSet<Konut>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> AVM { get; set; }
        public Nullable<bool> Belediye { get; set; }
        public Nullable<bool> Cami { get; set; }
        public Nullable<bool> DenizeSifir { get; set; }
        public Nullable<bool> Eczane { get; set; }
        public Nullable<bool> EglenceMerkezi { get; set; }
        public Nullable<bool> Fuar { get; set; }
        public Nullable<bool> Hastane { get; set; }
        public Nullable<bool> Lise { get; set; }
        public Nullable<bool> Market { get; set; }
        public Nullable<bool> Park { get; set; }
        public Nullable<bool> PolisMerkezi { get; set; }
        public Nullable<bool> SaglikOcagi { get; set; }
        public Nullable<bool> SemtPazari { get; set; }
        public Nullable<bool> SporSalonu { get; set; }
        public Nullable<bool> Üniversite { get; set; }
        public Nullable<bool> İlkokul_Ortaokul { get; set; }
        public Nullable<bool> İtfaiye { get; set; }
        public Nullable<bool> SehirMerkezi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konut> Konut { get; set; }
    }
}
