//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulasim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ulasim()
        {
            this.Konut = new HashSet<Konut>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Anayol { get; set; }
        public Nullable<bool> Avrasya_Tuneli { get; set; }
        public Nullable<bool> Bagaz_Koprusu { get; set; }
        public Nullable<bool> Cadde { get; set; }
        public Nullable<bool> Dolmus { get; set; }
        public Nullable<bool> E5 { get; set; }
        public Nullable<bool> HavaAlanı { get; set; }
        public Nullable<bool> Marmaray { get; set; }
        public Nullable<bool> Metro { get; set; }
        public Nullable<bool> Metrobüs { get; set; }
        public Nullable<bool> Otobus_Duragı { get; set; }
        public Nullable<bool> Sahil { get; set; }
        public Nullable<bool> TEM { get; set; }
        public Nullable<bool> İskele { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Konut> Konut { get; set; }
    }
}
